CREATE TABLE [dbo].[Driver]
(
	[ID] BIGINT IDENTITY(1,1) NOT NULL,
	[EnrolmentID] BIGINT NOT NULL,
	[OrganizationID] BIGINT NOT NULL DEFAULT 1, 
	[FirstName] NVARCHAR(50) NULL, 
	[SecondName] NVARCHAR(50) NULL, 
	[LastName] NVARCHAR(50) NULL, 
	[NationalNumber] NVARCHAR(50) NOT NULL, 
	[Address] NVARCHAR(MAX) NULL, 
	[Mobile] NVARCHAR(50) NOT NULL,
	[Phone] NVARCHAR(50) NULL,
	[Birthday] DATETIME NULL, 
	[SocialStatus] SMALLINT NULL, 
	[IsActive] BIT NOT NULL DEFAULT 1, 
	[IsHaveProblem] BIT NOT NULL, 
	[Reason] NVARCHAR(MAX) NULL,
	[IsOnline] BIT NOT NULL DEFAULT 0, 
	[ModifiedDate] DATETIME NOT NULL DEFAULT GETUTCDATE(), 
    [CreationDate] DATETIME NOT NULL DEFAULT GETUTCDATE(), 
    [IsDeleted] BIT NOT NULL DEFAULT 0, 
    CONSTRAINT [PK_Driver] PRIMARY KEY ([ID] ASC), 
	CONSTRAINT [FK_Driver_Enrolment] FOREIGN KEY([EnrolmentID]) REFERENCES [dbo].[Enrolment] ([ID]),
	CONSTRAINT [FK_Driver_Organization] FOREIGN KEY([OrganizationID]) REFERENCES [dbo].[Organization] ([ID]),
	CONSTRAINT [UK_DriverNationalNumber] UNIQUE NONCLUSTERED ([NationalNumber]),
)
