// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IDeliverObjects.Objects
{
    public partial class Attachment
    {
        public int Id { get; set; }
        public long ModuleId { get; set; }
        public int ModuleType { get; set; }
        public string Path { get; set; }
        public string FileName { get; set; }
        public string Extension { get; set; }
        public int AttachmentType { get; set; }
        public DateTime CreationDate { get; set; }
        public bool IsDeleted { get; set; }
        public long? CreatorId { get; set; }
        public string GroupId { get; set; }
    }
}