// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IDeliverObjects.Objects
{
    public partial class DriverDetail
    {
        public int Id { get; set; }
        public int DriverId { get; set; }
        public int? JobTime { get; set; }
        public DateTime? FromTime { get; set; }
        public DateTime? ToTime { get; set; }
        public DateTime? StartJob { get; set; }
        public string College { get; set; }
        public string University { get; set; }
        public string Major { get; set; }
        public string GraduationYear { get; set; }
        public string Estimate { get; set; }
        public string AvancedStudies { get; set; }
        public DateTime? CreationDate { get; set; }
        public bool? IsDeleted { get; set; }

        public virtual Driver Driver { get; set; }
    }
}