// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IDeliverObjects.Objects
{
    public partial class DriverCase
    {
        public long Id { get; set; }
        public long DriverId { get; set; }
        public short Status { get; set; }
        public bool IsOnline { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public DateTime ModifiedDate { get; set; }
        public DateTime CreationDate { get; set; }
        public bool IsDeleted { get; set; }

        public virtual Driver Driver { get; set; }
    }
}