// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IDeliverObjects.Objects
{
    public partial class Driver
    {
        public Driver()
        {
            DriverDetails = new HashSet<DriverDetail>();
            DriverSchadules = new HashSet<DriverSchadule>();
        }

        public int Id { get; set; }
        public long EnrolmentId { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public int? Mobile { get; set; }
        public int? Mobile2 { get; set; }
        public DateTime? Birthday { get; set; }
        public int? SocialStatus { get; set; }
        public DateTime? CreationDate { get; set; }
        public bool? IsDeleted { get; set; }
        public bool? IsActive { get; set; }
        public bool? IsHaveProblem { get; set; }
        public string Reason { get; set; }

        public virtual Enrolment Enrolment { get; set; }
        public virtual ICollection<DriverDetail> DriverDetails { get; set; }
        public virtual ICollection<DriverSchadule> DriverSchadules { get; set; }
    }
}