// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IDeliverObjects.Objects
{
    public partial class DriverOrder
    {
        public long Id { get; set; }
        public long DriverId { get; set; }
        public long OrderId { get; set; }
        public short Status { get; set; }
        public string Note { get; set; }
        public DateTime ModifiedDate { get; set; }
        public DateTime CreationDate { get; set; }
        public bool IsDeleted { get; set; }

        public virtual Driver Driver { get; set; }
        public virtual Order Order { get; set; }
    }
}